service: serverless-zkm

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1

functions:
  generateRandomNumber:
    handler: handler.generateRandomNumber
    events:
      - http:
          path: /api/generateRandomNumber
          method: get
          cors: true